spring:
  application:
    name: temm
  datasource:
    url: jdbc:mysql://localhost:3306/temm?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://developers.google.com/oauthplayground"
            authorization-grant-type: authorization_code
            scope: [openid, profile, email]
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token

jwt:
  access-token-validity: 3600000 # 1시간
  refresh-token-validity: 2592000000 # 30일
  secret-key: dGlja2V0aW5nLXNlcnZpY2UtYXV0aGVudGljYXRpb24=
